services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "8080:8080"
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped
    environment:
      WEBUI_AUTH: "False"
      OLLAMA_BASE_URL: http://ollama:11434 
volumes:
  ollama:
  open-webui: